-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MCU_tester IS
   PORT( 
      Instruction_out : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      PC              : IN     STD_LOGIC_VECTOR ( 9 DOWNTO 0 );
      KEY1            : OUT    STD_LOGIC; 
      KEY2            : OUT    STD_LOGIC;  
      KEY3            : OUT    STD_LOGIC;
      clock           : OUT    STD_LOGIC;
      reset           : OUT    STD_LOGIC;
      PC_ENABLE       : OUT    STD_LOGIC ;
      SW_in				 : OUT 	STD_LOGIC_VECTOR( 7 DOWNTO 0 ) 
 
   );

-- Declarations

END MCU_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MCU_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';
   SIGNAL mw_U_2pulse : std_logic :='0';
   SIGNAL mw_U_3pulse : std_logic :='0';




BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
  -- mw_U_0disable_clk <= TRUE AFTER 100000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   reset <= mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '0',
         '0' AFTER 50 ns,
         '1' AFTER 120 ns;
      WAIT;
    END PROCESS u_1pulse_proc;

   KEY3 <= mw_U_2pulse;
   KEY2 <= '1'; 
   KEY1  <= '1';
   PROCESS
   BEGIN
   mw_U_2pulse <= 
          '1',
          '0' AFTER 4050 ns,
          '1' AFTER 4250 ns;
       WAIT;
     END PROCESS;

    PC_ENABLE  <= '1';
   --  PROCESS
   --  BEGIN
   --  mw_U_3pulse <= 
   --        '1',
   --        '0' AFTER 50 ns,
   --        '1' AFTER 350 ns;
   --     WAIT;
   --   END PROCESS;

   -- Instance port mappings.
   SW_in <= "01010101";  


END struct;
